### ISSUE TITLE
Update GitHub verified URL for i18next organization

### ISSUE THREAD

**Issue by jayaddison** [i18next/.github#1]
## 🚀 Feature Proposal
Hi folks - this is only an idea, and should be taken with a grain of salt especially if it could have resulting side-effects elsewhere.

While looking at the `i18next/i18next` repository source, I spotted a few links to the (non-HTTPS) i18next homepage at http://i18next.com

This automaticaly redirects to https://www.i18next.com and a secure session is established between browser and server.

I considered updating some of the i18next documentation links to use HTTPS by default, but if that's desirable, I figured that it might first be sensible for the i18next GitHub organization to verify the https://www.i18next.com domain ([doc ref](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/verifying-your-organizations-domain)).

A clear and concise description of what the feature is.
- Update the domain for the [`i18next` GitHub organization](https://github.com/i18next) to `https://www.i18next.com`
- Verify the updated domain following GitHub's [documentation](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/verifying-your-organizations-domain)

## Motivation

Sending people directly to an HTTPS-enabled version of the `i18next` homepage saves a step for users and the web server.  Before updating documentation and links, it makes sense to verify that the updated links maintain organizational integrity.  Even though top-level domains are generally controlled by the same people/organizations as subdomains, it can be useful to verify it anyway.

**Comment by jamuhl** [comment]
The root domain is owned by me and already verified. It's safe to change those links...

**Comment by jayaddison** [comment]
Thanks for confirming; merged via https://github.com/i18next/i18next/pull/1545
